Bcftools dev
moka-guys/dnanexus_swiss_army_SNP_bcftools_filter pull request #1
Opened 2020-03-24 15:28 UTC by natashapinto

SNP VCF filters applied using bcftools in swiss army knife

2020-03-24 15:43 UTC, aledj2 requested changes
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_swiss_army_snp_bcftools_filter/1)* status: 1 of 3 files reviewed, 13 unresolved discussions (waiting on @aledj2 and @natashapinto)

___
*[README.md, line 5 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_swiss_army_snp_bcftools_filter/1#-M3CBKtXDlgmdeeIGrZ1:-M3CBKtXDlgmdeeIGrZ2:bevf3j) ([raw file](https://github.com/moka-guys/dnanexus_swiss_army_snp_bcftools_filter/blob/dac86bccf1086bb74c2676fea64528498e03a572/README.md#L5)):*
> ```Markdown
> 
> ## Input
> The input files for this app includes a bash script(snp_bcftools*.sh) and compressed GVCF file(s) produced by Sentieon Fastq to VCF app (*markdup_Haplotyper.g.vcf.gz).
> ```

input of csv, fasta or bed files mentioned in the sh script. could these be downloaded, eg wget project:fileid so they don't change?
___
*[README.md, line 9 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_swiss_army_snp_bcftools_filter/1#-M3CAHTw3GFbNYlSSLFV:-M3CAHTw3GFbNYlSSLFW:b-5rsc6g) ([raw file](https://github.com/moka-guys/dnanexus_swiss_army_snp_bcftools_filter/blob/dac86bccf1086bb74c2676fea64528498e03a572/README.md#L9)):*
> ```Markdown
> The app's "command line" input is used to execute the above bash script. This command is recorded in command_line_input.sh
> 
> ## How the app works
> ```

no mention of tabix and indexing of vcf. decompress not uncompress, annotates the header how? unused alleles? 
___
*[README.md, line 10 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_swiss_army_snp_bcftools_filter/1#-M3CCF9r6ahEX_A69tAJ:-M3CCF9r6ahEX_A69tAK:bj7v9mm) ([raw file](https://github.com/moka-guys/dnanexus_swiss_army_snp_bcftools_filter/blob/dac86bccf1086bb74c2676fea64528498e03a572/README.md#L10)):*
> ```Markdown
> 
> ## How the app works
> snp_bcftools*.sh loops through all the GCVF files, uncompresses them, annotates the header, removes any unused alleles, removes any variants with DP < 5 and decomposes the GVCF using BCFtools (v1.9).
> ```

actually is this accurate? what about the conversion to vcf?
___
*[README.md, line 13 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_swiss_army_snp_bcftools_filter/1#-M3CAQ3G01iRIZGSvTLE:-M3CAQ3G01iRIZGSvTLF:b-iwch23) ([raw file](https://github.com/moka-guys/dnanexus_swiss_army_snp_bcftools_filter/blob/dac86bccf1086bb74c2676fea64528498e03a572/README.md#L13)):*
> ```Markdown
> 
> ## Output
> Filtered VCF files are named filtered_normalised.vcf.gz The app's "output folder" argument can be used to output files to the expected directory.
> ```

can be? perhaps the shell script can mirror the output location (/output) by creating that folder? (not sure if that works).
maybe more explicit, the files are output to / unless the output location is specified when setting off the app?
___
*[snp_bcftools.sh, line 1 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_swiss_army_snp_bcftools_filter/1#-M3CBePs4yR9B8H_Sfv6:-M3CBePs4yR9B8H_Sfv7:bpy925x) ([raw file](https://github.com/moka-guys/dnanexus_swiss_army_snp_bcftools_filter/blob/dac86bccf1086bb74c2676fea64528498e03a572/snp_bcftools.sh#L1)):*
> ```Shell
> for fasta in *.fa.gz; do
> ```

not sure why these are used. as described in readme comments maybe the specific file could be linked to eg `dx cat project-123:fileid > fasta.fa `
___
*[snp_bcftools.sh, line 3 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_swiss_army_snp_bcftools_filter/1#-M3CBD8T2kuMVJYD0yFH:-M3CBD8T2kuMVJYD0yFI:b-m27nif) ([raw file](https://github.com/moka-guys/dnanexus_swiss_army_snp_bcftools_filter/blob/dac86bccf1086bb74c2676fea64528498e03a572/snp_bcftools.sh#L3)):*
> ```Shell
> for fasta in *.fa.gz; do
> 	gunzip $fasta
> 	ls
> ```

is this needed?
___
*[snp_bcftools.sh, line 6 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_swiss_army_snp_bcftools_filter/1#-M3CBwpc1WujIrKCu8rM:-M3CBwpc1WujIrKCu8rN:bfj7wjj) ([raw file](https://github.com/moka-guys/dnanexus_swiss_army_snp_bcftools_filter/blob/dac86bccf1086bb74c2676fea64528498e03a572/snp_bcftools.sh#L6)):*
> ```Shell
> 	fasta_file=*.fa
> done
> for header in *csv; do
> ```

as above, can we hard code this input?
___
*[snp_bcftools.sh, line 9 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_swiss_army_snp_bcftools_filter/1#-M3CBznk0dtj0RvT5x5e:-M3CBznk0dtj0RvT5x5f:bhkwi0y) ([raw file](https://github.com/moka-guys/dnanexus_swiss_army_snp_bcftools_filter/blob/dac86bccf1086bb74c2676fea64528498e03a572/snp_bcftools.sh#L9)):*
> ```Shell
> 	header_file=header
> done
> for bed in *bed; do
> ```

hard code?
___
*[snp_bcftools.sh, line 21 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_swiss_army_snp_bcftools_filter/1#-M3CCJDU10sEjcLLnCgF:-M3CCJDV5uXIIm3V76uJ:b-9ilauz) ([raw file](https://github.com/moka-guys/dnanexus_swiss_army_snp_bcftools_filter/blob/dac86bccf1086bb74c2676fea64528498e03a572/snp_bcftools.sh#L21)):*
> ```Shell
>     tabix -p vcf $vcf
>     echo "convert to vcf"
>     bcftools convert --gvcf2vcf -R $bedfile -f $fasta_file -Oz -o $vcf_filename.sites.vcf.gz $vcf
> ```

maybe some comments? what are the arguments used?
___
*[snp_bcftools.sh, line 24 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_swiss_army_snp_bcftools_filter/1#-M3CCNs5EE6rTJ6KblJx:-M3CCNs5EE6rTJ6KblJy:b-rl0ec9) ([raw file](https://github.com/moka-guys/dnanexus_swiss_army_snp_bcftools_filter/blob/dac86bccf1086bb74c2676fea64528498e03a572/snp_bcftools.sh#L24)):*
> ```Shell
>     ls
>     echo "remove unused alleles"
>     bcftools view --trim-alt-alleles -Oz -o $vcf_filename.sites_present.vcf.gz $vcf_filename.sites.vcf.gz
> ```

comments?what are the arguments used?
___
*[snp_bcftools.sh, line 26 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_swiss_army_snp_bcftools_filter/1#-M3CCPHP1b30ceTs5GWa:-M3CCPHP1b30ceTs5GWb:b-rl0ec9) ([raw file](https://github.com/moka-guys/dnanexus_swiss_army_snp_bcftools_filter/blob/dac86bccf1086bb74c2676fea64528498e03a572/snp_bcftools.sh#L26)):*
> ```Shell
>     bcftools view --trim-alt-alleles -Oz -o $vcf_filename.sites_present.vcf.gz $vcf_filename.sites.vcf.gz
>     echo "annotating header"
>     bcftools annotate -h $header -Oz -o $vcf_filename.sites_present_reheader.vcf.gz $vcf_filename.sites_present.vcf.gz
> ```

comments?what are the arguments used?
___
*[snp_bcftools.sh, line 28 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_swiss_army_snp_bcftools_filter/1#-M3CCQLb2kojuCsmxPlr:-M3CCQLb2kojuCsmxPls:b57wtx7) ([raw file](https://github.com/moka-guys/dnanexus_swiss_army_snp_bcftools_filter/blob/dac86bccf1086bb74c2676fea64528498e03a572/snp_bcftools.sh#L28)):*
> ```Shell
>     bcftools annotate -h $header -Oz -o $vcf_filename.sites_present_reheader.vcf.gz $vcf_filename.sites_present.vcf.gz
>     echo "filter"
>     bcftools filter -i 'FMT/DP>5' -m x -Oz -o $vcf_filename.sites_present_reheader_filtered.vcf.gz $vcf_filename.sites_present_reheader.vcf.gz
> ```

comments? what are the arguments used?
___
*[snp_bcftools.sh, line 30 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_swiss_army_snp_bcftools_filter/1#-M3CCRGBEhytpxqWvO2P:-M3CCRGBEhytpxqWvO2Q:b-7ntazp) ([raw file](https://github.com/moka-guys/dnanexus_swiss_army_snp_bcftools_filter/blob/dac86bccf1086bb74c2676fea64528498e03a572/snp_bcftools.sh#L30)):*
> ```Shell
>     bcftools filter -i 'FMT/DP>5' -m x -Oz -o $vcf_filename.sites_present_reheader_filtered.vcf.gz $vcf_filename.sites_present_reheader.vcf.gz
>     echo "normalise and decompose"
>     bcftools norm -m - -Oz -o $vcf_filename.sites_present_reheader_filtered_normalised.vcf.gz $vcf_filename.sites_present_reheader_filtered.vcf.gz
> ```

comments - what are the arguments used?


<!-- Sent from Reviewable.io -->

2020-06-26 13:43 UTC, aledj2 requested changes
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_swiss_army_snp_bcftools_filter/1)* status: 1 of 3 files reviewed, 18 unresolved discussions (waiting on @aledj2 and @natashapinto)

___
*[snp_bcftools.sh, line 10 at r2](https://reviewable.io/reviews/moka-guys/dnanexus_swiss_army_snp_bcftools_filter/1#-MAkphQ558UnP2q6ifyi:-MAkphQ558UnP2q6ifyj:b-6l6btj) ([raw file](https://github.com/moka-guys/dnanexus_swiss_army_snp_bcftools_filter/blob/2c8d805cae0fa938f5cbb3b9afe7b2f17ac4b012/snp_bcftools.sh#L10)):*
> ```Shell
> 
> #get BED file 
> bedfile=*newkit_bedfile_b38.bed 
> ```

I assume we will have a PAN number for the snp identity kit, I think having *.bed would be most flexible.
___
*[snp_bcftools.sh, line 25 at r2](https://reviewable.io/reviews/moka-guys/dnanexus_swiss_army_snp_bcftools_filter/1#-MAkqH0nAbHqO8nJztwu:-MAkqH0nAbHqO8nJztwv:b-x9ohr0) ([raw file](https://github.com/moka-guys/dnanexus_swiss_army_snp_bcftools_filter/blob/2c8d805cae0fa938f5cbb3b9afe7b2f17ac4b012/snp_bcftools.sh#L25)):*
> ```Shell
>     tabix -p vcf $vcf
>     #conert gvcf to vcf
>     #-R region of interest -f fasta_file 
> ```

it's the -Oz command which is hardest to understand  from this command
___
*[snp_bcftools.sh, line 30 at r2](https://reviewable.io/reviews/moka-guys/dnanexus_swiss_army_snp_bcftools_filter/1#-MAkqbrl2JRcvSEsfhca:-MAkqbrl2JRcvSEsfhcb:b-6x1ctt) ([raw file](https://github.com/moka-guys/dnanexus_swiss_army_snp_bcftools_filter/blob/2c8d805cae0fa938f5cbb3b9afe7b2f17ac4b012/snp_bcftools.sh#L30)):*
> ```Shell
>     echo "remove unused alleles"
>     #only keep SNPs of interest
>     bcftools view --trim-alt-alleles -Oz -o $vcf_filename.sites_present.vcf.gz $vcf_filename.sites.vcf.gz
> ```

as above the -Oz commands are least obvious
___
*[snp_bcftools.sh, line 33 at r2](https://reviewable.io/reviews/moka-guys/dnanexus_swiss_army_snp_bcftools_filter/1#-MAkqlTo5VCn7hd5RcFh:-MAkqlTo5VCn7hd5RcFi:be6be50) ([raw file](https://github.com/moka-guys/dnanexus_swiss_army_snp_bcftools_filter/blob/2c8d805cae0fa938f5cbb3b9afe7b2f17ac4b012/snp_bcftools.sh#L33)):*
> ```Shell
>     echo "annotating header"
>     #annotate header with kit name Nimagen SNP Genotyping v2.0
>     bcftools annotate -h $header_file -Oz -o $vcf_filename.sites_present_reheader.vcf.gz $vcf_filename.sites_present.vcf.gz
> ```

what does -h do? add in that header?
___
*[snp_bcftools.sh, line 35 at r2](https://reviewable.io/reviews/moka-guys/dnanexus_swiss_army_snp_bcftools_filter/1#-MAkr-mW2F6cq6lnCrF3:-MAkr-mW2F6cq6lnCrF4:b-5u2oqo) ([raw file](https://github.com/moka-guys/dnanexus_swiss_army_snp_bcftools_filter/blob/2c8d805cae0fa938f5cbb3b9afe7b2f17ac4b012/snp_bcftools.sh#L35)):*
> ```Shell
>     bcftools annotate -h $header_file -Oz -o $vcf_filename.sites_present_reheader.vcf.gz $vcf_filename.sites_present.vcf.gz
>     echo "filter"
>     #Only keep SNPs with read depth more than 5
> ```

-i only keep SNPs with DP (within format column) > 5
___
*[snp_bcftools.sh, line 36 at r2](https://reviewable.io/reviews/moka-guys/dnanexus_swiss_army_snp_bcftools_filter/1#-MAkqvA6AjKPja-BfO_8:-MAkqvA6AjKPja-BfO_9:b-gsescm) ([raw file](https://github.com/moka-guys/dnanexus_swiss_army_snp_bcftools_filter/blob/2c8d805cae0fa938f5cbb3b9afe7b2f17ac4b012/snp_bcftools.sh#L36)):*
> ```Shell
>     echo "filter"
>     #Only keep SNPs with read depth more than 5
>     #-m sets filter column to pass
> ```

what is x? 
___
*[snp_bcftools.sh, line 40 at r2](https://reviewable.io/reviews/moka-guys/dnanexus_swiss_army_snp_bcftools_filter/1#-MAkrIaB7QUxju47ymNn:-MAkrIaB7QUxju47ymNo:baoo08e) ([raw file](https://github.com/moka-guys/dnanexus_swiss_army_snp_bcftools_filter/blob/2c8d805cae0fa938f5cbb3b9afe7b2f17ac4b012/snp_bcftools.sh#L40)):*
> ```Shell
>     #decompose vcf; split biallelic regions to seperate lines. 
>     echo "normalise and decompose"
>     bcftools norm -m - -Oz -o $vcf_filename.sites_present_reheader_filtered_normalised.vcf.gz $vcf_filename.sites_present_reheader_filtered.vcf.gz
> ```

you've exmplained -m above, assume it's the same here what is the dash after -m?


<!-- Sent from Reviewable.io -->

2020-06-26 14:24 UTC, aledj2 requested changes
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_swiss_army_snp_bcftools_filter/1)* status: 1 of 3 files reviewed, 12 unresolved discussions (waiting on @aledj2 and @natashapinto)

___
*[snp_bcftools.sh, line 40 at r3](https://reviewable.io/reviews/moka-guys/dnanexus_swiss_army_snp_bcftools_filter/1#-MAl00Pi8GKAs_WLN2Yi:-MAl00Pi8GKAs_WLN2Yj:b-ys2fac) ([raw file](https://github.com/moka-guys/dnanexus_swiss_army_snp_bcftools_filter/blob/ec87a49371881f65dacb82ba3802a5b58ac31c3d/snp_bcftools.sh#L40)):*
> ```Shell
>     echo "filter"
>     #-i only keep SNPs with DP (within format column) > 5
>     #-mx The "x" mode resets filters of sites which pass to "PASS"
> ```

-m space x in cmd
___
*[snp_bcftools.sh, line 43 at r3](https://reviewable.io/reviews/moka-guys/dnanexus_swiss_army_snp_bcftools_filter/1#-MAl-sur7A2Jywd-yZsF:-MAl-sur7A2Jywd-yZsG:b-88pqyl) ([raw file](https://github.com/moka-guys/dnanexus_swiss_army_snp_bcftools_filter/blob/ec87a49371881f65dacb82ba3802a5b58ac31c3d/snp_bcftools.sh#L43)):*
> ```Shell
>     #-0z specifies output format z=zipped
>     bcftools filter -i 'FMT/DP>5' -m x -Oz -o $vcf_filename.sites_present_reheader_filtered.vcf.gz $vcf_filename.sites_present_reheader.vcf.gz
>     #decompose vcf; split biallelic regions to seperate lines. 
> ```

bcftools norm also decomposes?


<!-- Sent from Reviewable.io -->

2020-06-26 14:32 UTC, aledj2 requested changes
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_swiss_army_snp_bcftools_filter/1)* status: 1 of 3 files reviewed, 14 unresolved discussions (waiting on @aledj2 and @natashapinto)

___
*[README.md, line 10 at r4](https://reviewable.io/reviews/moka-guys/dnanexus_swiss_army_snp_bcftools_filter/1#-MAl0pET3KgH9XZunzTi:-MAl0pET3KgH9XZunzTj:brue2md) ([raw file](https://github.com/moka-guys/dnanexus_swiss_army_snp_bcftools_filter/blob/d986f219918b7395a0baf8b43ef506cdc00959a3/README.md#L10)):*
> ```Markdown
> 
> ## How the app works
> snp_bcftools*.sh loops through all the GCVfs,creates an index, converts to vcf, keeps SNPs of interest,annotates header with kit name uncompresses them, annotates the header, only keeps SNPs with DP > 5 and decomposes the VCF using BCFtools (v1.9).
> ```

Appears this line is duplicated? maybe bullet points would be clearer?
For each GVCF:
* creates an index using tabix
* converts from gVCF to VCF (bcftools convert)
* etc etc - please also see extra comments I've raised
___
*[snp_bcftools.sh, line 30 at r3](https://reviewable.io/reviews/moka-guys/dnanexus_swiss_army_snp_bcftools_filter/1#-MAl1MKj7BzUZYENjhG4:-MAl1MKj7BzUZYENjhG5:b-8hy29r) ([raw file](https://github.com/moka-guys/dnanexus_swiss_army_snp_bcftools_filter/blob/ec87a49371881f65dacb82ba3802a5b58ac31c3d/snp_bcftools.sh#L30)):*
> ```Shell
>     bcftools convert --gvcf2vcf -R $bedfile -f $fasta_file -Oz -o $vcf_filename.sites.vcf.gz $vcf
>     echo "remove unused alleles"
>     #only keep SNPs of interest
> ```

SNPs of interest - does this mean based on coordinate or any variants not predicted to be in the genotype?


<!-- Sent from Reviewable.io -->

2020-06-26 16:16 UTC, natashapinto reviewed
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_swiss_army_snp_bcftools_filter/1)* status: 1 of 3 files reviewed, 14 unresolved discussions (waiting on @aledj2 and @preciserobot)

___
*[README.md, line 5 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_swiss_army_snp_bcftools_filter/1#-M3CBKtXDlgmdeeIGrZ1:-M3qBaX568cZXaRpYAIA:b6q19zv) ([raw file](https://github.com/moka-guys/dnanexus_swiss_army_snp_bcftools_filter/blob/dac86bccf1086bb74c2676fea64528498e03a572/README.md#L5)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

input of csv, fasta or bed files mentioned in the sh script. could these be downloaded, eg wget project:fileid so they don't change?
</blockquote></details>

Specified file names instead
___
*[README.md, line 9 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_swiss_army_snp_bcftools_filter/1#-M3CAHTw3GFbNYlSSLFV:-M3GcQ6W1Mws9gbbWvgQ:b-896fix) ([raw file](https://github.com/moka-guys/dnanexus_swiss_army_snp_bcftools_filter/blob/dac86bccf1086bb74c2676fea64528498e03a572/README.md#L9)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

no mention of tabix and indexing of vcf. decompress not uncompress, annotates the header how? unused alleles? 
</blockquote></details>

Done.
___
*[README.md, line 10 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_swiss_army_snp_bcftools_filter/1#-M3CCF9r6ahEX_A69tAJ:-M3GcTKRBC5nxeV1lFzw:bt58o4e) ([raw file](https://github.com/moka-guys/dnanexus_swiss_army_snp_bcftools_filter/blob/dac86bccf1086bb74c2676fea64528498e03a572/README.md#L10)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

actually is this accurate? what about the conversion to vcf?
</blockquote></details>

sorry corrected it now. I got confused
___
*[README.md, line 13 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_swiss_army_snp_bcftools_filter/1#-M3CAQ3G01iRIZGSvTLE:-M3GfiBt30nEnv0z6kjV:b-7neyse) ([raw file](https://github.com/moka-guys/dnanexus_swiss_army_snp_bcftools_filter/blob/dac86bccf1086bb74c2676fea64528498e03a572/README.md#L13)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

can be? perhaps the shell script can mirror the output location (/output) by creating that folder? (not sure if that works).
maybe more explicit, the files are output to / unless the output location is specified when setting off the app?
</blockquote></details>

For now I just changed the wording to be more explicit like you suggested.
___
*[README.md, line 10 at r4](https://reviewable.io/reviews/moka-guys/dnanexus_swiss_army_snp_bcftools_filter/1#-MAl0pET3KgH9XZunzTi:-MAlN-64D4gpg3WLvMlo:b-896fix) ([raw file](https://github.com/moka-guys/dnanexus_swiss_army_snp_bcftools_filter/blob/d986f219918b7395a0baf8b43ef506cdc00959a3/README.md#L10)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

Appears this line is duplicated? maybe bullet points would be clearer?
For each GVCF:
* creates an index using tabix
* converts from gVCF to VCF (bcftools convert)
* etc etc - please also see extra comments I've raised
</blockquote></details>

Done.
___
*[snp_bcftools.sh, line 1 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_swiss_army_snp_bcftools_filter/1#-M3CBePs4yR9B8H_Sfv6:-M3LB2ht3j1OYY4ZnQOs:b-896fix) ([raw file](https://github.com/moka-guys/dnanexus_swiss_army_snp_bcftools_filter/blob/dac86bccf1086bb74c2676fea64528498e03a572/snp_bcftools.sh#L1)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

not sure why these are used. as described in readme comments maybe the specific file could be linked to eg `dx cat project-123:fileid > fasta.fa `
</blockquote></details>

Done.
___
*[snp_bcftools.sh, line 3 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_swiss_army_snp_bcftools_filter/1#-M3CBD8T2kuMVJYD0yFH:-M3qC5s31CrpVUbxro9M:b-niw3e7) ([raw file](https://github.com/moka-guys/dnanexus_swiss_army_snp_bcftools_filter/blob/dac86bccf1086bb74c2676fea64528498e03a572/snp_bcftools.sh#L3)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

is this needed?
</blockquote></details>

nope, removed
___
*[snp_bcftools.sh, line 6 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_swiss_army_snp_bcftools_filter/1#-M3CBwpc1WujIrKCu8rM:-M3LB3dlDWVYCeMRSdAH:b-896fix) ([raw file](https://github.com/moka-guys/dnanexus_swiss_army_snp_bcftools_filter/blob/dac86bccf1086bb74c2676fea64528498e03a572/snp_bcftools.sh#L6)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

as above, can we hard code this input?
</blockquote></details>

Done.
___
*[snp_bcftools.sh, line 9 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_swiss_army_snp_bcftools_filter/1#-M3CBznk0dtj0RvT5x5e:-M3LB4sK1Q8gOVCsd9zg:b-896fix) ([raw file](https://github.com/moka-guys/dnanexus_swiss_army_snp_bcftools_filter/blob/dac86bccf1086bb74c2676fea64528498e03a572/snp_bcftools.sh#L9)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

hard code?
</blockquote></details>

Done.
___
*[snp_bcftools.sh, line 11 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_swiss_army_snp_bcftools_filter/1#-M3C9qpI6MeX-wnK0t86-r1-11:-M3qCB2RD7ApiJdiycBA:b-i5n8ja) ([raw file](https://github.com/moka-guys/dnanexus_swiss_army_snp_bcftools_filter/blob/dac86bccf1086bb74c2676fea64528498e03a572/snp_bcftools.sh#L11)):*
<details><summary><i>Previously, preciserobot (David Brawand) wrote…</i></summary><blockquote>

So we just pick the last BED file if there are multiple?
Should be *.bed.
</blockquote></details>

Specified the BED file name instead; can't have multiple bed files
___
*[snp_bcftools.sh, line 24 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_swiss_army_snp_bcftools_filter/1#-M3CCNs5EE6rTJ6KblJx:-MAkuXmO2GsmkQXenfio:b-896fix) ([raw file](https://github.com/moka-guys/dnanexus_swiss_army_snp_bcftools_filter/blob/dac86bccf1086bb74c2676fea64528498e03a572/snp_bcftools.sh#L24)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

comments?what are the arguments used?
</blockquote></details>

Done.
___
*[snp_bcftools.sh, line 26 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_swiss_army_snp_bcftools_filter/1#-M3CCPHP1b30ceTs5GWa:-MAkuZwT-7ZSzUd-chqM:b-896fix) ([raw file](https://github.com/moka-guys/dnanexus_swiss_army_snp_bcftools_filter/blob/dac86bccf1086bb74c2676fea64528498e03a572/snp_bcftools.sh#L26)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

comments?what are the arguments used?
</blockquote></details>

Done.
___
*[snp_bcftools.sh, line 28 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_swiss_army_snp_bcftools_filter/1#-M3CCQLb2kojuCsmxPlr:-MAkutmA7v1EDEZ1QXtf:b-896fix) ([raw file](https://github.com/moka-guys/dnanexus_swiss_army_snp_bcftools_filter/blob/dac86bccf1086bb74c2676fea64528498e03a572/snp_bcftools.sh#L28)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

comments? what are the arguments used?
</blockquote></details>

Done.
___
*[snp_bcftools.sh, line 30 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_swiss_army_snp_bcftools_filter/1#-M3CCRGBEhytpxqWvO2P:-MAkuu9h2jLWIHqchz_G:b-896fix) ([raw file](https://github.com/moka-guys/dnanexus_swiss_army_snp_bcftools_filter/blob/dac86bccf1086bb74c2676fea64528498e03a572/snp_bcftools.sh#L30)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

comments - what are the arguments used?
</blockquote></details>

Done.
___
*[snp_bcftools.sh, line 10 at r2](https://reviewable.io/reviews/moka-guys/dnanexus_swiss_army_snp_bcftools_filter/1#-MAkphQ558UnP2q6ifyi:-MAksohi9aqi5geMo1f9:b-896fix) ([raw file](https://github.com/moka-guys/dnanexus_swiss_army_snp_bcftools_filter/blob/2c8d805cae0fa938f5cbb3b9afe7b2f1 [...]

2020-07-09 14:53 UTC, aledj2 requested changes
> Reviewed 1 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_swiss_army_snp_bcftools_filter/1)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @aledj2, @natashapinto, and @preciserobot)

___
*[snp_bcftools.sh, line 47 at r5](https://reviewable.io/reviews/moka-guys/dnanexus_swiss_army_snp_bcftools_filter/1#-MBo2Vy4EyfcC_p8xPub:-MBo2Vy4EyfcC_p8xPuc:b-2rshjr) ([raw file](https://github.com/moka-guys/dnanexus_swiss_army_snp_bcftools_filter/blob/7748d494dc770afc8d3572eea77ee5bfcd4b3985/snp_bcftools.sh#L47)):*
> ```Shell
>     #-0z specifies output format z=zipped
>     echo "normalise and decompose"
>     -m split multiallelic sites into biallelic records (-) 
> ```

should this be a comment? and should it be:
#-m - =  split multiallelic sites into biallelic records 


<!-- Sent from Reviewable.io -->

2020-07-09 15:00 UTC, natashapinto reviewed
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_swiss_army_snp_bcftools_filter/1)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @aledj2 and @preciserobot)

___
*[snp_bcftools.sh, line 47 at r5](https://reviewable.io/reviews/moka-guys/dnanexus_swiss_army_snp_bcftools_filter/1#-MBo2Vy4EyfcC_p8xPub:-MBo4cnW38Zo55S8yJDD:b-896fix) ([raw file](https://github.com/moka-guys/dnanexus_swiss_army_snp_bcftools_filter/blob/7748d494dc770afc8d3572eea77ee5bfcd4b3985/snp_bcftools.sh#L47)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

should this be a comment? and should it be:
#-m - =  split multiallelic sites into biallelic records 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-07-09 15:49 UTC, aledj2 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_swiss_army_snp_bcftools_filter/1#-:-MBoG5sXBaIN5caPs4Y9:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-07-09 15:49 UTC, merged